name = "dsr-notes-sync"
main = "dsr-notes-sync.js"
compatibility_date = "2025-01-01"
workers_dev = true

# Created 2026-09-10 with:  npx wrangler kv namespace create NOTES_KV
kv_namespaces = [
  { binding = "NOTES_KV", id = "4de9735191854f8f9fe98175150bdfc2" }
]

# SYNC_TOKEN is a secret, not a var:  npx wrangler secret put SYNC_TOKEN
